<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>slim</string>
	</array>
	<key>name</key>
	<string>Slim</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#embedded-engine-css</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-engine-sass</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-engine-stylus</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-engine-scss</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-engine-coffee</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-engine-javascript</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#slim-block-comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#slim-line-comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#slim-escaped-content</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ruby-logic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ruby-content</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ruby-embedded</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-unenclosed</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-enclosed-1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-enclosed-2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-enclosed-3</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#illegal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>brackets-content-1</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#brackets-content-1</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>brackets-content-2</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#brackets-content-2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>brackets-content-3</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#brackets-content-3</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>embedded-engine-coffee</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(coffee:)\s.*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1(	|  ))|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
		<key>embedded-engine-css</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(css:)\s.*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1(	|  ))|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<key>embedded-engine-javascript</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(javascript:)\s.*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1(	|  ))|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>embedded-engine-sass</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(sass:)\s.*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1(	|  ))|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sass</string>
				</dict>
			</array>
		</dict>
		<key>embedded-engine-scss</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(scss:)\s.*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1(	|  ))|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.scss</string>
				</dict>
			</array>
		</dict>
		<key>embedded-engine-stylus</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(styl:)\s.*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1(	|  ))|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.stylus</string>
				</dict>
			</array>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>^\s*+[^\w=.#|'-].*$</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<key>ruby-content</key>
		<dict>
			<key>begin</key>
			<string>==?'? </string>
			<key>end</key>
			<string>(?&lt;=do\n)|(?&lt;!\\|,)\n</string>
			<key>name</key>
			<string>source.ruby.rails.embedded.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>ruby-embedded</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)#{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>source.ruby.rails.embedded.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>ruby-logic</key>
		<dict>
			<key>begin</key>
			<string>^\s*(?=-)</string>
			<key>end</key>
			<string>(?&lt;=do\n)|(?&lt;!\\)\n</string>
			<key>name</key>
			<string>source.ruby.rails.embedded.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>slim-block-comment</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(/)\s.*$</string>
			<key>end</key>
			<string>^(?!(\1(	|  ))|\s*$)</string>
			<key>name</key>
			<string>comment.block.slim</string>
		</dict>
		<key>slim-escaped-content</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)[|'][ 	]</string>
			<key>end</key>
			<string>^(?!(\1(	|  ))|\s*$)</string>
			<key>name</key>
			<string>text.slim.escaped-content</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ruby-embedded</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>slim-line-comment</key>
		<dict>
			<key>match</key>
			<string>^\s*/.*$</string>
			<key>name</key>
			<string>comment.line.slash.slim</string>
		</dict>
		<key>tag-enclosed-1</key>
		<dict>
			<key>begin</key>
			<string>(([A-Za-z.#][\w.#-]*\w)++|\w)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>tag-enclosed-1</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ruby-content</string>
				</dict>
			</array>
		</dict>
		<key>tag-enclosed-2</key>
		<dict>
			<key>begin</key>
			<string>(([A-Za-z.#][\w.#-]*\w)++|\w)\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ruby-content</string>
				</dict>
			</array>
		</dict>
		<key>tag-enclosed-3</key>
		<dict>
			<key>begin</key>
			<string>(([A-Za-z.#][\w.#-]*\w)++|\w)\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ruby-content</string>
				</dict>
			</array>
		</dict>
		<key>tag-param-name</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s\[\{\(])\w[\w:-]*(?==)</string>
			<key>name</key>
			<string>entity.other.attribute-name.slim</string>
		</dict>
		<key>tag-param-value</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\w)=(?!\s)</string>
			<key>end</key>
			<string>\s|(?=[\]\}\)]|:\s)</string>
			<key>name</key>
			<string>source.ruby.rails.embedded.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#brackets-content-1</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#brackets-content-2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#brackets-content-3</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>tag-params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-param-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-param-value</string>
				</dict>
			</array>
		</dict>
		<key>tag-unenclosed</key>
		<dict>
			<key>begin</key>
			<string>(?:^\s*|(?!^):\s*)((?:([A-Za-z.#][\w.#-]*\w)++|[A-Za-z]))(?![\[\{\(])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ruby-content</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ruby-embedded</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-unenclosed</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-enclosed-1</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-enclosed-2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-enclosed-3</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.slim</string>
	<key>uuid</key>
	<string>71DE10E5-E691-4A97-B8E8-AC0D5E60FCAB</string>
</dict>
</plist>
